openapi: 3.0.3
info:
  title: School Veil API Project
  version: 1.0.0
  description: A school management system
paths:
  /api/v1/schools/:
    get:
      operationId: api_v1_schools_list
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/School'
          description: ''
    post:
      operationId: api_v1_schools_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/School'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/School'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/School'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/School'
          description: ''
  /api/v1/schools/{slug}/:
    get:
      operationId: api_v1_schools_retrieve
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/School'
          description: ''
    put:
      operationId: api_v1_schools_update
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/School'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/School'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/School'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/School'
          description: ''
    patch:
      operationId: api_v1_schools_partial_update
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedSchool'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedSchool'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedSchool'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/School'
          description: ''
    delete:
      operationId: api_v1_schools_destroy
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/v1/schools/{slug}/schools/:
    get:
      operationId: api_v1_schools_schools_list
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/School'
          description: ''
    post:
      operationId: api_v1_schools_schools_create
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/School'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/School'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/School'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/School'
          description: ''
  /api/v1/schools/{slug}/schools/{slug}/:
    get:
      operationId: api_v1_schools_schools_retrieve
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/School'
          description: ''
    put:
      operationId: api_v1_schools_schools_update
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/School'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/School'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/School'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/School'
          description: ''
    patch:
      operationId: api_v1_schools_schools_partial_update
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedSchool'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedSchool'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedSchool'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/School'
          description: ''
    delete:
      operationId: api_v1_schools_schools_destroy
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    PatchedSchool:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        address:
          type: string
          maxLength: 255
        phone_number:
          type: string
          maxLength: 20
        email:
          type: string
          format: email
          maxLength: 255
        location:
          type: string
          maxLength: 100
        logo:
          type: string
          format: uri
          nullable: true
        status:
          $ref: '#/components/schemas/StatusEnum'
        slug:
          type: string
          nullable: true
          maxLength: 50
          pattern: ^[-a-zA-Z0-9_]+$
        temp_password:
          type: string
          nullable: true
          maxLength: 128
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
    School:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        address:
          type: string
          maxLength: 255
        phone_number:
          type: string
          maxLength: 20
        email:
          type: string
          format: email
          maxLength: 255
        location:
          type: string
          maxLength: 100
        logo:
          type: string
          format: uri
          nullable: true
        status:
          $ref: '#/components/schemas/StatusEnum'
        slug:
          type: string
          nullable: true
          maxLength: 50
          pattern: ^[-a-zA-Z0-9_]+$
        temp_password:
          type: string
          nullable: true
          maxLength: 128
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - address
      - created_at
      - email
      - id
      - name
      - phone_number
      - updated_at
    StatusEnum:
      enum:
      - approved
      - pending
      - rejected
      type: string
      description: |-
        * `approved` - Approved
        * `pending` - Pending
        * `rejected` - Rejected
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
