# Generated by Django 4.1.7 on 2023-03-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_motto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='temp_password',
            new_name='password',
        ),
    ]
